### ISSUE TITLE
Build failure in Launchpad bionic

### ISSUE THREAD

**Issue by sarnold** [VCTLabs/redis-ipc#6]
Tried removing hardening flags, etc, no joy (builds fine locally).

https://launchpad.net/~nerdboy/+archive/ubuntu/embedded/+build/21812918

**Comment by SJLC** [comment]
Your build log doesn't show finding hiredis or json-c, and it doesn't have anything about pkg-config like my local log. Does it help if you install pkg-config in the builder?

**Comment by sarnold** [comment]
Yup, missing pkg-config...
